language: node_js
node_js: 
    - "12"
dist: trusty 
services:
    - mongodb
env: 
    - NODE_ENV=ci PORT=3500
cache: 
    directories:
        - node_modules
        - client/node_modules
install: 
    - npm install
    - npm run build
script:
    - nohup npm run start &
    - sleep 3
    - npm run test
